# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "aa64c567-ffbd-4e87-8f1b-731201deae45"

default_platform :ios
xcode_select "/Applications/Xcode8.2.app"

# Fastfile actions accept additional configuration, but

# info which you can add here later
lane :beta do
  # cocoapods
  gym(
    workspace: "HFUTer3.xcworkspace",
	output_directory: "./fastlane/build",
	scheme: "HFUTer3"
  )

   # testflight(skip_waiting_for_build_processing: true)
   firim
end
